Generyki - poprawki, tłumaczenie, uzupełnienie opisów
java-academy/generycznaPlansza pull request #1
Opened 2019-07-16 12:58 UTC by WojTechM

Duplikat mojego warsztatu znajduje się też w innym repozytorium. Jak uda nam się dojść do akceptowalnej wersji, to trzeba ją wrzucić również tam.

2019-08-20 08:15 UTC, LIttleAncientForestKami reviewed
@kamroj ma popatrzeć jeszcze, mi się póki co podoba, ale jestem na 7 klasce z 23 zatem :-)

2019-08-20 08:15 UTC, LIttleAncientForestKami commented on pom.xml
> +            <version>7.0.0-beta3</version>
Beta? Czemu?

2019-08-20 08:15 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie1.java
> +}
Te opisy powodują uśmiech na twarzy. :100:

2019-08-20 08:15 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie2.java
> +class Wór {
:D

2019-08-20 08:37 UTC, LIttleAncientForestKami requested changes
Kilka drobnych zmian jakie bym chciał, ale ja jestem na TAK. Czekamy na Kamila.

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie5.java
> +            List<Integer> ints = Arrays.asList(1, 2); // Robimy listę Integerów
Nie byłoby od rzeczy zrobić <code> wokół tego i podobnych kawałków.

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on pom.xml
>      <groupId>Drusil</groupId>
Do zmiany, choć niekoniecznie tu i w tym zadaniu.

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie2.java
> +package warsztaty_wprowadzajace;
Paczka do zmiany.

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie2.java
> +public class Zadanie2<T> {
Podoba mi się, że jest kawałek gotowy i na podobieństwo trzeba coś zrobić. :+1:

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie3.java
> + */
:+1: za Javadoc i :+1: za ten Javadoc

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie3.java
> +        */
Tu jeszcze przydałoby się podsumowanie z nazwami ostrzeżeń / błędów jakie lecą. Ale to moja chciwość mówi, zaakceptuję bez tego.

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie4.java
> +
Niepotrzebne aż dwie puste linie, jedna wystarczy

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie4.java
> + * <p><i>// Im mniej o tym myślisz tym bardziej logiczne się to wydaje.</i></p>
:+1:

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie4.java
> +        choć nie będzie zbyt logiczne. Jeśli mi nie ufasz to sprawdź. Jeśli mi ufasz, to coś z tobą nie tak.
:+1:

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie4.java
> +        Nasza metoda przyjmuje dowonle obiekty które są Klonowable, nawet jeśli nie są wokalistami, i to jest problem.
dowonle -> dowolne

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie6.java
> +        // No ale jest problem. Oczywiście, że jest jakiś problem...
:+1:

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie6.java
> +        Ale kompilator niestety nie. A przynajmniej tak to wygląda.
:+1:

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie6.java
> +        Nasza metoda przyjmuje konsumenta wokalistów (dalej zwany kanibalem), a nie konsumenta obiektów.
Kanibal... :D

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie7.java
> +package warsztaty_wprowadzajace;
Dla klaru (w związku z uwagą zmiana paczki wcześniej): zmiana paczki potem. Teraz paczka jak tu jest OK ("warsztaty_wprowadzajace").

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/package-info.java
> + * <i>z</i><b>n</b><em>a</em><sub>c</sub><sup>z</sup><small>n</small><ins>i</ins><sub>k</sub><sup>i</sup> HTML.
No nieźle! :D Dużo tych znaczników.

2019-08-20 08:37 UTC, LIttleAncientForestKami commented on src/main/java/zadanie_koderskie/package-info.java
> + * // w IntelliJ naciśnij 'Ctrl' + 'q' aby wyświetlić ze wsparciem dla tagów html.
znaczników

2019-08-20 13:52 UTC, kamroj requested changes

2019-08-20 13:52 UTC, kamroj commented on src/main/java/warsztaty_wprowadzajace/Zadanie1.java
> +        // Robota w Javie 4 skończona. Wróć do warsztatowego repo.
Można dodać jeszcze by podpatrzyli sobie tamtejszą implementacje np interfejsu List.

2019-08-20 13:52 UTC, kamroj commented on src/main/java/warsztaty_wprowadzajace/Zadanie1.java
> +        // <String> mówi kompilatorowi, że w naszej liście będą tylko instancje klasy 'String'
Fajnie dodać info na temat magicznej mocy kompilatora do odgadywania typu. Przed javą 7 nie mogliśmy stosować pustego diamencika po prawej stronie <>.

2019-08-20 13:52 UTC, kamroj commented on src/main/java/warsztaty_wprowadzajace/Zadanie3.java
> +                List<String> l = new ArrayList<String>();
Fajnie byłoby dodać, że poprzez wymazywanie typów nie możemy bawić się polimorfizmem statycznym jak na przykładzie poniżej:

```
void metoda1 (List<Integer> kolekcja) { ... }
void metoda2 (List<String> kolekcja) { ... }
 ```

2019-08-20 13:52 UTC, kamroj commented on src/main/java/warsztaty_wprowadzajace/Zadanie4.java
> +        Ważna notka - przy generykach używamy tylko słówka 'extends', nigdy 'implements', niezależnie czy mówimy
Szukałem kiedyś czemu nie mogli zostawić dla interfejsów słówka kluczowego `implements` ale się nie doszukałem, więc jak masz jakieś racjonalne wytłumaczenie to fajnie by było tu wstawić :)

2019-08-20 13:52 UTC, kamroj commented on src/main/java/warsztaty_wprowadzajace/Zadanie7.java
> +package warsztaty_wprowadzajace;
czy to nie złamanie konwencji nazywania paczek i powinna być ona zapisana jako `warsztatywprowadzajace` ? Poprawcie mnie jeśli się mylę.

2019-08-20 13:52 UTC, kamroj commented on src/main/java/warsztaty_wprowadzajace/package-info.java
> + * zwracam się do czytającego jakby był mężczyzną. Wszystkie panie urażone tym faktem
Co za szowinistyczna świnia 😄

2019-08-20 13:52 UTC, kamroj commented on src/main/java/zadanie_koderskie/Field.java
> +package zadanie_koderskie;
tak jak wyżej, wg konwencji `zadaniekoderskie`

2019-08-20 16:15 UTC, WojTechM commented on src/main/java/warsztaty_wprowadzajace/Zadanie5.java
> +            List<Integer> ints = Arrays.asList(1, 2); // Robimy listę Integerów
Gdyby to był javadoc - jasne. Ale w komentarzu?

2019-08-20 16:16 UTC, WojTechM commented on pom.xml
>      <groupId>Drusil</groupId>
Na? Skoro i tak poprawiam, to mogę zrobić to od razu.

2019-08-20 16:20 UTC, WojTechM commented on src/main/java/warsztaty_wprowadzajace/Zadanie4.java
> +        Ważna notka - przy generykach używamy tylko słówka 'extends', nigdy 'implements', niezależnie czy mówimy
Bo tak chciało życie...

2019-08-21 11:58 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie5.java
> +            List<Integer> ints = Arrays.asList(1, 2); // Robimy listę Integerów
Słusznie. :D

2019-08-21 12:02 UTC, LIttleAncientForestKami commented on pom.xml
>      <groupId>Drusil</groupId>
Grupa: ja.workshops
Artefakt: generics

2019-08-21 12:07 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie7.java
> +package warsztaty_wprowadzajace;
Koniec końców i tak ją zmieniamy potem zatem...
Link do prawidłowej konwencji: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html 
Podkreślnik (oficjalnie) jest używany jeśli domena posiada myślnik albo wprowadziłaby słowo kluczowe czy zaczyna się od numerka. Ale nie ma zakazów jego używania w innych sytuacjach. Tu decyzja była by użyć podkreślnika dla czytelności.

2019-08-21 12:08 UTC, LIttleAncientForestKami commented on src/main/java/zadanie_koderskie/Field.java
> +package zadanie_koderskie;
jak wyżej

2019-08-21 12:16 UTC, LIttleAncientForestKami commented on src/main/java/warsztaty_wprowadzajace/Zadanie4.java
> +        Ważna notka - przy generykach używamy tylko słówka 'extends', nigdy 'implements', niezależnie czy mówimy
Mogli. Ale po co mieliby? Extends sugeruje kierunek. Super również. Implements nie ma takich ograniczeń wbudowanych. Interfejsy rozszerzamy via `extends` również.
https://docs.oracle.com/javase/specs/jls/se12/html/jls-4.html#jls-TypeBound
https://docs.oracle.com/javase/specs/jls/se12/html/jls-4.html#jls-ClassOrInterfaceType

2019-08-21 12:32 UTC, WojTechM commented on pom.xml
>      <groupId>Drusil</groupId>
Polski i angielski? Nie lepiej ujednolicić?
Grupa: ja.warsztaty
Artefakt: generyki
+ czy powinienem też poprawić paczki?
warsztaty_wprowadzajace => ja.warsztaty.generyki.warsztatywprowadzajace

2019-08-21 12:35 UTC, WojTechM commented on src/main/java/warsztaty_wprowadzajace/Zadanie1.java
> +        // <String> mówi kompilatorowi, że w naszej liście będą tylko instancje klasy 'String'
Polecasz jakieś materiały wyjaśniające tę "magiczną moc kompilatora"? :P

2019-08-21 14:25 UTC, LIttleAncientForestKami commented
#response_container_BBPPID{font-family: initial; font-size:initial; color: #646464;}  Mile widziane! Niekonieczne.                                                                                                                                                                          Od: notifications@github.comWysłano: 21 sierpnia 2019 2:32 PMDo: generycznaPlansza@noreply.github.comOdp. do: reply@reply.github.comDW: Tomasz.Borek@gmail.com; review_requested@noreply.github.comTemat: Re: [java-academy/generycznaPlansza] Generyki - poprawki, tłumaczenie, uzupełnienie opisów (#1)  @WojTechM commented on this pull request.







In pom.xml:

> @@ -7,6 +7,14 @@

     <groupId>Drusil</groupId>



Polski i angielski? Nie lepiej ujednolicić?

Grupa: ja.warsztaty

Artefakt: generyki

czy powinienem też poprawić paczki?

warsztaty_wprowadzajace => ja.warsztaty.generyki.warsztatywprowadzajace



—You are receiving this because your review was requested.Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-24 22:31 UTC, LIttleAncientForestKami approved these changes
Mam pytania, ale o detale. Będę wciągał, chyba, że ktoś coś napisze w stylu "NIEEE! BŁAGAM NIEEE!" w ciągu najbliższych x godzin, gdzie x < 48.

2019-09-24 22:31 UTC, LIttleAncientForestKami commented on pom.xml
> +    <groupId>ja.workshops</groupId>
:+1:

2019-09-24 22:31 UTC, LIttleAncientForestKami commented on pom.xml
>          <maven.compiler.source>1.8</maven.compiler.source>
Poza zakresem tej zmiany ale ciekawym opinii Waszych: chcemy 11tkę tutaj? Jeśli tak, otwórzmy kwita na potem. Jest późno i ja nie wiem.

2019-09-24 22:31 UTC, LIttleAncientForestKami commented on src/test/java/warsztatywprowadzajace/WórTest.java
> +import static org.testng.AssertJUnit.assertEquals;
Czemu tak?

2019-09-24 22:33 UTC, LIttleAncientForestKami commented
@kamroj chciałbym rzecz zamknąć w ciągu 2 dni, zatem zerknij proszę czy Twoje komentarze są uwzględnione.

@WojTechM dobra robota, dzięki!

2019-09-25 08:27 UTC, kamroj commented on src/main/java/warsztaty_wprowadzajace/Zadanie1.java
> +        // <String> mówi kompilatorowi, że w naszej liście będą tylko instancje klasy 'String'
Co prawda przedawnione ale podsyłam: https://docs.oracle.com/javase/tutorial/java/generics/genTypeInference.html

2019-09-25 08:31 UTC, kamroj commented
@WojTechM czy celowo nie wrzucałeś moich sugestii (oprócz zmiany nazwy pakietów)? Jeżeli tak to @LIttleAncientForestKami można zamknąć, jeśli nie, to podtrzymuje moje "NIEEE! BŁAGAM NIEEE!".

2019-09-25 17:09 UTC, LIttleAncientForestKami commented
> @WojTechM czy celowo nie wrzucałeś moich sugestii (oprócz zmiany nazw pakietów)? Jeżeli tak to @LIttleAncientForestKami można zamknąć, jeśli nie, to podtrzymuje moje "NIEEE! BŁAGAM NIEEE!".

Myślę, że @WojTechM miał tam jakieś pytania. Natomiast mam prośbę - stwórzmy na to nowego kwita. Jeśli mógłbyś go opisać @kamroj . Tu już dużo zrobiono w myśl "zasady skauta" i jest lepiej niż było i bym to już wciągnął by potem przejść się po kwizie a potem wrócić do - mając kwita nie ucieknie nam to. Jeśli Cię to urządza, klepnij zgodę i wciągam.

2019-11-05 10:34 UTC, kamroj approved these changes

2019-11-17 21:01 UTC, merged